package dbfundamentals

import (
	"database/sql"
	"fmt"
)

// SQL operations in database/sql are separated into:
// - Exec: used for statements that don't return rows (CREATE, INSERT, UPDATE, DELETE).
// - QueryRow: used for queries expected to return at most one row.
// - Query: used for queries returning multiple rows.
// Parameter placeholders (e.g. "?", "$1") prevent SQL Injection by separating query structure from user input.

type Student struct {
	ID    int
	Name  string
	Age   int
	Grade string
}

// CreateStudentsTable creates a basic demo table.
func CreateStudentsTable(db *sql.DB) error {
	query := `
	CREATE TABLE IF NOT EXISTS students (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT NOT NULL,
		age INTEGER NOT NULL,
		grade TEXT NOT NULL
	);`

	// Exec executes a query without returning any rows.
	_, err := db.Exec(query)
	if err != nil {
		return fmt.Errorf("failed to create table: %w", err)
	}
	return nil
}

// InsertStudent inserts a row and returns the new auto-increment ID.
func InsertStudent(db *sql.DB, name string, age int, grade string) (int64, error) {
	query := `INSERT INTO students (name, age, grade) VALUES (?, ?, ?)`

	// Bind parameters "?" to arguments to prevent SQL injection.
	result, err := db.Exec(query, name, age, grade)
	if err != nil {
		return 0, fmt.Errorf("insert failed: %w", err)
	}

	// LastInsertId returns the integer generated by the database in response to a command.
	id, err := result.LastInsertId()
	if err != nil {
		return 0, fmt.Errorf("failed to retrieve last insert ID: %w", err)
	}

	return id, nil
}

// GetStudentByID retrieves a single student.
func GetStudentByID(db *sql.DB, id int64) (Student, error) {
	query := `SELECT id, name, age, grade FROM students WHERE id = ?`
	var s Student

	// QueryRow returns at most one row. The database connection is released
	// as soon as Scan is called.
	err := db.QueryRow(query, id).Scan(&s.ID, &s.Name, &s.Age, &s.Grade)
	if err != nil {
		if err == sql.ErrNoRows {
			return Student{}, fmt.Errorf("student with ID %d not found", id)
		}
		return Student{}, fmt.Errorf("query failed: %w", err)
	}

	return s, nil
}

// GetStudentsByGrade retrieves multiple students.
func GetStudentsByGrade(db *sql.DB, grade string) ([]Student, error) {
	query := `SELECT id, name, age, grade FROM students WHERE grade = ?`

	// Query returns a rows structure representing the database cursor.
	rows, err := db.Query(query, grade)
	if err != nil {
		return nil, fmt.Errorf("query failed: %w", err)
	}
	// CRITICAL: Always defer closing rows. If you forget to close rows,
	// database connections will remain open and leak!
	defer rows.Close()

	var students []Student

	// Loop through rows using Next.
	for rows.Next() {
		var s Student
		// Scan reads columns in the current row into dest variables.
		err := rows.Scan(&s.ID, &s.Name, &s.Age, &s.Grade)
		if err != nil {
			return nil, fmt.Errorf("failed to scan student row: %w", err)
		}
		students = append(students, s)
	}

	// Retrieve any error encountered during iteration.
	if err = rows.Err(); err != nil {
		return nil, fmt.Errorf("rows iteration error: %w", err)
	}

	return students, nil
}

// InsertStudentsPrepared demonstrates using Prepared Statements.
// Prepared statements compile the query once and allow fast execution of multiple inputs.
func InsertStudentsPrepared(db *sql.DB, batch []Student) error {
	query := `INSERT INTO students (name, age, grade) VALUES (?, ?, ?)`

	// Prepare compiles the SQL query on the database side.
	stmt, err := db.Prepare(query)
	if err != nil {
		return fmt.Errorf("failed to prepare statement: %w", err)
	}
	// Always close statements to release server-side resources.
	defer stmt.Close()

	for _, s := range batch {
		// Execute the prepared statement with values.
		_, err := stmt.Exec(s.Name, s.Age, s.Grade)
		if err != nil {
			return fmt.Errorf("failed to execute prepared statement for %s: %w", s.Name, err)
		}
	}

	return nil
}
